application: stats-api-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /poll_stats
  secure: always
  login: admin
  script: main.app
- url: /call_twiml
  secure: always
  script: main.app

libraries:
- name: ssl
  version: 'latest'
- name: webapp2
  version: '2.5.2'
- name: yaml
  version: '3.10'
